# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-nbdev-vscode',
                'doc_host': 'https://wbarfuss.github.io',
                'git_url': 'https://github.com/wbarfuss/test-nbdev-vscode',
                'lib_path': 'test_nbdev_vscode'},
  'syms': {'test_nbdev_vscode.core': {'test_nbdev_vscode.core.foo': ('core.html#foo', 'test_nbdev_vscode/core.py')}}}
